CREATE TABLE IF NOT EXISTS DATASOURCE_DETAILS(
    UID VARCHAR(100)  NOT NULL DEFAULT public.uuid_generate_v4(),
    METADATA_UID VARCHAR NOT NULL,
    DESCRIPTION TEXT,
    SUMMARY VARCHAR,
    TITLE VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DATASOURCE_DETAILS PRIMARY KEY (UID),
    FOREIGN KEY (METADATA_UID) REFERENCES METADATA(UID)
    );
