CREATE TABLE IF NOT EXISTS DATASOURCE(
    UID VARCHAR(100)  NOT NULL DEFAULT public.uuid_generate_v4(),
    METADATA_UID VARCHAR NOT NULL,
    DATA BYTEA,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (METADATA_UID) REFERENCES METADATA(UID),
    CONSTRAINT PK_DATASOURCE PRIMARY KEY (UID)
    );
