CREATE TABLE IF NOT EXISTS DATASOURCE_DETAILS_TAGS(
    DATASOURCE_DETAILS_UID VARCHAR NOT NULL DEFAULT public.uuid_generate_v4(),
    TAG_UID VARCHAR NOT NULL,
    CONSTRAINT PK_DETAILS_TAGS PRIMARY KEY (DATASOURCE_DETAILS_UID, TAG_UID),
    FOREIGN KEY (DATASOURCE_DETAILS_UID) REFERENCES DATASOURCE_DETAILS(UID),
    FOREIGN KEY (TAG_UID) REFERENCES TAGS(UID)
);
